version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
#    healthcheck:
#      test: ["CMD", "echo ruok | nc 127.0.0.1 2181"]
#      interval: 10s
#      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # 외부(호스트=IDE)에서 localhost:9092 로, 컨테이너 간에도 0.0.0.0:9092 으로 바인딩
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
#        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
#      interval: 10s
#      retries: 5
