name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build and Push to Public ECR"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            mkdir -p ~/sw_be_deploy
            cd ~/sw_be_deploy

            echo "${{ secrets.DOCKER_COMPOSE_YML }}" > docker-compose.yml

            aws ecr-public get-login-password --region us-east-1 \
              | docker login --username AWS --password-stdin public.ecr.aws

            docker compose pull app

            docker compose down
            docker compose up -d
