name: CD - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI - Build and Push to Public ECR"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            IMAGE_URL="${{ secrets.ECR_PUBLIC_URL }}"
            IMAGE_TAG="latest"

            docker stop sw-be-app || true
            docker rm sw-be-app || true

            aws ecr-public get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin public.ecr.aws

            docker pull $IMAGE_URL:$IMAGE_TAG

            docker run -d --name sw-be-app -p 8080:8080 $IMAGE_URL:$IMAGE_TAG
